services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  kong-database:
    image: postgres:12
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - kong_data:/var/lib/postgresql/data

  kong-migration:
    image: kong:3.9
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
    depends_on:
      kong-database:
        condition: service_healthy
    restart: on-failure

  kong:
    image: kong:3.9
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_GUI_URL: https://localhost:8445
      KONG_ADMIN_GUI_PATH: /
      KONG_SSL_CERT: /ssl/cert.pem
      KONG_SSL_CERT_KEY: /ssl/key.pem
    depends_on:
      kong-migration:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
      - "8445:8445"
    volumes:
      - ./ssl:/ssl
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  mongodb:
    image: mongo:5.0
    command: mongod --port 27017
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
      - ./data/configdb:/data/configdb

  orion:
    image: fiware/orion:3.7.0
    ports:
      - 1026:1026
    environment:
      ORION_MONGO_HOST: mongodb:27017
      ORION_PORT: 1026
      ORION_LOG_LEVEL: INFO
    depends_on:
      - mongodb

  terraform:
    image: hashicorp/terraform:1.7
    volumes:
      - ./terraform:/workspace
    working_dir: /workspace
    environment:
      - TF_LOG=INFO
    depends_on:
      kong:
        condition: service_healthy
    entrypoint: [""]
    command: ["terraform", "init"]

volumes:
  node_modules:
  kong_data:
