name: Docker Build Test
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create certs
        run: openssl req -newkey rsa:2048 -nodes -keyout ssl/key.pem -x509 -days 365 -out ssl/cert.pem

      - name: docker builds
        run: docker compose build

      - name: up services
        run: docker compose up -d

      - name: terraform apply for kong
        run: docker compose run --rm --no-deps terraform terraform apply -auto-approve
